version: '3'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: always
    network_mode: "host"

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    network_mode: "host"

  dlsmon:
    build:
      context: .
      args:
        USER: "1000"
    ports:
      - 8080:8080
    environment:
      DLSMON_ADDR: "127.0.0.1:8080"
      DLSMON_CMD: "ssh -oHostkeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -i .ssh/key root@riko.lan \"/etc/init.d/dsl_control status\""
      DLSMON_SLEEP: "1"
    network_mode: "host"
    volumes:
      - ./ssh:/root/.ssh
