version: '3'

services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: always
    network_mode: "host"
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=10y"
    network_mode: "host"
    restart: always

  dlsmon:
    build:
      context: .
      args:
        USER: "1000"
    ports:
      - 8080:8080
    environment:
      DLSMON_ADDR: "127.0.0.1:8080"
      DLSMON_CMD: "ssh -oHostkeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -oStrictHostKeyChecking=no -i .ssh/key root@riko.lan \"/etc/init.d/dsl_control status\""
      DLSMON_SLEEP: "120"
    network_mode: "host"
    volumes:
      - ./ssh:/root/.ssh
    restart: always

volumes:
  grafana-data:
  prometheus-data:
